# Generated by Django 5.2 on 2025-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="media/", verbose_name="Фото блюда"
            ),
        ),
    ]
