# Generated by Django 5.2 on 2025-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="quantity",
            field=models.CharField(
                blank=True,
                help_text="Пример: 400 грамм, 6 зубчиков (необязательно)",
                max_length=50,
                null=True,
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                help_text="Пример: Помидор",
                max_length=50,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="diet_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                to="recipes.diettype",
                verbose_name="Типы питания",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                help_text="Пример: Спагетти Карбонара",
                max_length=100,
                unique=True,
                verbose_name="Название",
            ),
        ),
    ]
