# Generated by Django 5.2 on 2025-04-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_ingredient_quantity_alter_ingredient_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="quantity",
        ),
    ]
